#pragma config(Sensor, in5,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in6,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in7,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*----------------------------------------------------------------------------------------------------*\
|*                           									- VERKEFNI 5 -             					                    *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses 3 VEX Line Follower Sensors to track a black line on a light(er) surface.       *|
|*  																																														   		*|
\*----------------------------------------------------------------------------------------------------*/

task main()
{
  wait1Msec(2000);

  int threshold = 505;

  while(true)
  {

    displayLCDCenteredString(0, "LEFT  CNTR  RGHT");
    displayLCDPos(1,0);
    displayNextLCDNumber(SensorValue(lineFollowerLEFT));
    displayLCDPos(1,6);
    displayNextLCDNumber(SensorValue(lineFollowerCENTER));
    displayLCDPos(1,12);
    displayNextLCDNumber(SensorValue(lineFollowerRIGHT));



    if(SensorValue(lineFollowerRIGHT) > threshold)
    {
     	if(vexRT[Btn7D] == 1)//if button 7 D is pressed the motor stops
			{
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
			}
			else{
      motor[leftMotor]  = 63;
      motor[rightMotor] = 0;
    }
    }

    if(SensorValue(lineFollowerCENTER) > threshold)
    {
      if(vexRT[Btn7D] == 1)//if button 7 D is pressed the motor stops
			{
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
			}
			else{
      motor[leftMotor]  = 63;
      motor[rightMotor] = 63;
    	}
    }

    if(SensorValue(lineFollowerLEFT) > threshold)
    {
      if(vexRT[Btn7D] == 1)//if button 7 D is pressed the motor stops
		{
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
		}
		else{
      motor[leftMotor]  = 0;
      motor[rightMotor] = 63;
    }
    }
  }
}

