#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl11, sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*----------------------------------------------------------------------------------------------------*\
|*                                   			  - Verkefni 4 -              		                      	  *|
|*                                    ROBOTC on VEX 2.0 CORTEX                                        *|
|* In this program the robot will start when the lights turn on and it will use the sensor that it has*|
|*      													to drive without hitting anything   															  *|
|       																																															*|
\*----------------------------------------------------------------------------------------------------*/


const float WHEELBASE = 3.33;



//kodi ur verkefni 2
void TurnRight (int deg)
{
	while (abs(SensorValue[rightEncoder]) < deg * WHEELBASE)
	{
		if(vexRT[Btn7D] == 1)//if button 7 D is pressed the motor stops
		{
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
		}
		else
			{
			motor[leftMotor] = -127;
			motor[rightMotor] = 127;
			}
	}
}

void TurnLeft (int deg)
{
	while (abs(SensorValue[leftEncoder]) < deg * WHEELBASE)
	{
		if(vexRT[Btn7D] == 1)//if button 7 D is pressed the motor stops
		{
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
		}
		else
		{
			motor[leftMotor] = 127;
			motor[rightMotor] = -127;
		}
	}
}

void ResetEncoder()
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;


}
task main()
{
	wait1Msec(2000)
	 while(SensorValue(lightSensor) < 300) // While the ambient lightSensor reads a value less than 200
		{

			for(int i = 1; i < 1000; i++)
			{
				while(SensorValue(sonarSensor) > 30  || SensorValue(sonarSensor) == -1)//the robot will drive when the sonar cant sense a object within 30 cm
				{
					motor[rightMotor] = 127;
					motor[leftMotor]  = 127;
				}

				if(SensorValue(sonarSensor) = 30  || SensorValue(sonarSensor) == -1)//if robot gets 30 cm close to an object the robot will turn
				{
					ResetEncoder();
					TurnLeft(90);

				}
				//if(SensorValue(lightSensor) > 300) // While the ambient lightSensor reads a value less than 200
				//{}
		}
	}

	while(SensorValue(lightSensor) > 300) // While the ambient lightSensor reads a value less than 200
		{

	}
}
