#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                     -  1.Hluti Verkefni 3 -                                    	  *|
|*                                    ROBOTC on VEX 2.0 CORTEX                                        *|
|* 									This program lets the user control the robot with a remote controller				  	  *|
|*    		the user can control the arm with a press of a button and open and close the claw.				  *|
|*  	                                                   																					    *|
\*----------------------------------------------------------------------------------------------------*/
task main()
{

	while(1 == 1)
	{
			motor[leftMotor] = vexRT[Ch3] / 2;		//left joystick
			motor[rightMotor] = vexRT[Ch2] / 2;		//right joystick

			if(vexRT[Btn6D] == 1)//if button 6 D is pressed arm goes down
			{
				motor[armMotor] = 40;
			}

			else if(vexRT[Btn6U] == 1)//if button 6 U is pressed arm goes up
			{
				motor[armMotor] = -40;
			}
			else //else the motor stops
			{
       motor[armMotor] = 0;
			}

			if(vexRT[Btn8L]==1)//if button 8 L is pressed the claw opens
			{
				motor[clawMotor] = 40;
			}

			else if(vexRT[Btn8R] == 1)//if button 8 R is pressed the claw closes
			{
				motor[clawMotor] = -40;
			}
			else //this stops the claw motor
			{
       motor[clawMotor] = 0;
			}
	}


	//vexRT[Btn 7 D]

}
