#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                     -  3.Hluti Verkefni 2 -                                    	  *|
|*                                    ROBOTC on VEX 2.0 CORTEX                                        *|
|* This program instructs the robot to move forward 0,5m then do a 90 deg turn left then move another *|
|*  0.5m foward and do a 90deg turn righ then move forward again for 0.5m and turn 90deg right and    *|
|*  move forward 0.5m and then the robot stops	                                                      *|
|*          																																												  *|
|*                                                                                                    *|
|*          Notes: U 87,9cm   					Thermal = 7 * pi = 22		encoder = 360 = U											*|
|*          const int =87,9 /21,99 = 3,99 *90 = 359,1                                                 *|
|       																																															*|
\*----------------------------------------------------------------------------------------------------*/
const float WHEELBASE = 3.33;//3.99
const int BASELENGTH = 22;



void TurnRight (int deg)
{
	while (abs(SensorValue[rightEncoder]) < deg * WHEELBASE)
	{
		if(vexRT[Btn7D] == 1)//if button 7 D is pressed the motor stops
		{
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
		}
		else
			{
			motor[leftMotor] = -127;
			motor[rightMotor] = 127;
			}
	}
}

void TurnLeft (int deg)
{
	while (abs(SensorValue[leftEncoder]) < deg * WHEELBASE)
	{
		if(vexRT[Btn7D] == 1)//if button 7 D is pressed the motor stops
		{
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
		}
		else
		{
			motor[leftMotor] = 127;
			motor[rightMotor] = -127;
		}
	}
}
void drive (int dist)
{
	while(abs(SensorValue[rightEncoder]) < (dist/BASELENGTH)*360) {
		if(vexRT[Btn7D] == 1)//if button 7 D is pressed the motor stops
		{
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
		}
		else
		{
			motor(rightMotor) = 127;
			motor(leftMotor) = 127;
		}
	}
}


void ResetEncoder()
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;


}

task main()
{

		ResetEncoder();
		drive(50);

		ResetEncoder();
		TurnLeft(90);

		ResetEncoder();
		drive(50);

		ResetEncoder();
		TurnRight(90);

		ResetEncoder();
		drive(50);

		ResetEncoder();
		TurnRight(90);

		ResetEncoder();
		drive(50);


}
