#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                     -  2.Hluti Verkefni 2 -                                    	  *|
|*                                    ROBOTC on VEX 2.0 CORTEX                                        *|
|* This program instructs the robot to move forward 0,5m then backwards for 0,5m then forward 1m and  *|
|*      										backwards 1m and forward 1,5 then backwards 1,5m.   										  *|
|*                                                                                                    *|
|*          Notes: U 87,9cm   					Thermal = 7 * pi = 22		encoder = 360 = U											*|
|*          const int =87,9 /21,99 = 3,99 *90 = 359,1                                                 *|
|       																																															*|
\*----------------------------------------------------------------------------------------------------*/

//const float WHEELBASE = 3.33;//3.99
const int BASELENGTH = 22;

void drive (int dist)
{
	while(abs(SensorValue[rightEncoder]) < (dist/BASELENGTH)*360){
		motor(rightMotor) = 127;
		motor(leftMotor) = 127;
	}
}


void driveBackward (int dist)
{
	while(abs(SensorValue[rightEncoder]) < (dist/BASELENGTH)*360){
		motor(rightMotor) = -127;
		motor(leftMotor) = -127;
	}
}

void ResetEncoder()
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;


}

task main()
{

	int dist = 1;
		while(dist < 5)//runs 5 times
	{

				ResetEncoder();
				drive(50 * dist);
				ResetEncoder();
				driveBackward(50 * dist);
				dist ++;
		}



}
